"""offer advertised price basis

Revision ID: 37169c847521
Revises: ea6ba0419f26
Create Date: 2026-09-14 19:32:20.190618
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '37169c847521'
down_revision: str | None = 'ea6ba0419f26'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advertised_includes_fees', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('advertised_includes_fees')

    # ### end Alembic commands ###
