"""inbox, dealer domains, web form channel

Revision ID: b41f6a5baf5c
Revises: 37169c847521
Create Date: 2026-09-16 18:49:28.790470
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b41f6a5baf5c'
down_revision: str | None = '37169c847521'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('learned_from_interaction_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_dealer_domain_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learned_from_interaction_id'], ['interaction.id'], name=op.f('fk_dealer_domain_learned_from_interaction_id_interaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dealer_domain')),
    sa.UniqueConstraint('dealer_id', 'domain', name='uq_dealer_domain')
    )
    with op.batch_alter_table('dealer_domain', schema=None) as batch_op:
        batch_op.create_index('ix_dealer_domain_domain', ['domain'], unique=False)

    op.create_table('inbox_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_identifier', sa.String(length=300), nullable=False),
    sa.Column('thread_identifier', sa.String(length=300), nullable=True),
    sa.Column('rfc822_message_id', sa.String(length=400), nullable=True),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('from_email', sa.String(length=320), nullable=True),
    sa.Column('to_emails', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('label_ids', sa.String(length=500), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('promoted_interaction_id', sa.Integer(), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_reasons', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_inbox_message_campaign_id_campaign'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_inbox_message_dealer_id_dealer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promoted_interaction_id'], ['interaction.id'], name=op.f('fk_inbox_message_promoted_interaction_id_interaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbox_message'))
    )
    with op.batch_alter_table('inbox_message', schema=None) as batch_op:
        batch_op.create_index('ix_inbox_from', ['from_email'], unique=False)
        batch_op.create_index('ix_inbox_source', ['source_system', 'source_identifier'], unique=True)
        batch_op.create_index('ix_inbox_status', ['status', 'sent_at'], unique=False)
        batch_op.create_index('ix_inbox_thread', ['thread_identifier'], unique=False)

    with op.batch_alter_table('dealer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inquiry_alias', sa.String(length=320), nullable=True))
        batch_op.create_index('ix_dealer_alias', ['inquiry_alias'], unique=False)
        batch_op.drop_column('email_domains')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_domains', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_index('ix_dealer_alias')
        batch_op.drop_column('inquiry_alias')

    with op.batch_alter_table('inbox_message', schema=None) as batch_op:
        batch_op.drop_index('ix_inbox_thread')
        batch_op.drop_index('ix_inbox_status')
        batch_op.drop_index('ix_inbox_source')
        batch_op.drop_index('ix_inbox_from')

    op.drop_table('inbox_message')
    with op.batch_alter_table('dealer_domain', schema=None) as batch_op:
        batch_op.drop_index('ix_dealer_domain_domain')

    op.drop_table('dealer_domain')
    # ### end Alembic commands ###
