"""initial schema

Revision ID: ea6ba0419f26
Revises: 
Create Date: 2026-09-14 19:10:09.098110
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ea6ba0419f26'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('purchase_type', sa.String(length=20), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('target_make', sa.String(length=80), nullable=True),
    sa.Column('target_model', sa.String(length=120), nullable=True),
    sa.Column('target_trim', sa.String(length=120), nullable=True),
    sa.Column('target_powertrain', sa.String(length=60), nullable=True),
    sa.Column('color_preferences', sa.Text(), nullable=True),
    sa.Column('excluded_colors', sa.Text(), nullable=True),
    sa.Column('has_trade_in', sa.Boolean(), nullable=False),
    sa.Column('cash_available', sa.Boolean(), nullable=False),
    sa.Column('financing_acceptable', sa.String(length=30), nullable=False),
    sa.Column('wants_add_ons', sa.Boolean(), nullable=False),
    sa.Column('wants_maintenance_plan', sa.Boolean(), nullable=False),
    sa.Column('registration_state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('expected_tax_rate_bp', sa.Integer(), nullable=True),
    sa.Column('max_distance_miles', sa.Integer(), nullable=True),
    sa.Column('local_dealer_premium_cents', sa.Integer(), nullable=False),
    sa.Column('contact_preference', sa.String(length=40), nullable=False),
    sa.Column('avoid_phone_calls', sa.Boolean(), nullable=False),
    sa.Column('avoid_dealership_visits', sa.Boolean(), nullable=False),
    sa.Column('follow_up_after_hours', sa.Integer(), nullable=False),
    sa.Column('no_response_after_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyer_profile'))
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('target_max_price_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign'))
    )
    op.create_table('negotiation_state',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('is_active_pipeline', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_negotiation_state'))
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=True),
    sa.Column('last_history_id', sa.String(length=80), nullable=True),
    sa.Column('last_full_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_incremental_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cursor_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_state'))
    )
    with op.batch_alter_table('sync_state', schema=None) as batch_op:
        batch_op.create_index('ix_sync_provider', ['provider', 'account_email'], unique=True)

    op.create_table('dealer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email_domains', sa.String(length=500), nullable=True),
    sa.Column('distance_miles', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('state_code', sa.String(length=40), nullable=False),
    sa.Column('state_is_pinned', sa.Boolean(), nullable=False),
    sa.Column('state_changed_at', sa.DateTime(), nullable=True),
    sa.Column('first_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_dealer_campaign_id_campaign'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_code'], ['negotiation_state.code'], name=op.f('fk_dealer_state_code_negotiation_state')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dealer'))
    )
    with op.batch_alter_table('dealer', schema=None) as batch_op:
        batch_op.create_index('ix_dealer_state', ['state_code'], unique=False)

    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('actor_kind', sa.String(length=20), nullable=False),
    sa.Column('automation_evidence', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_contact_dealer_id_dealer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact'))
    )
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_index('ix_contact_email', ['email'], unique=False)

    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('trim', sa.String(length=120), nullable=True),
    sa.Column('body_style', sa.String(length=80), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('stock_number', sa.String(length=60), nullable=True),
    sa.Column('exterior_color', sa.String(length=80), nullable=True),
    sa.Column('interior_color', sa.String(length=80), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('msrp_cents', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('is_loaner', sa.Boolean(), nullable=True),
    sa.Column('damage_history', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_vehicle_campaign_id_campaign'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_vehicle_dealer_id_dealer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle'))
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index('ix_vehicle_vin', ['vin'], unique=False)

    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('normalized_content', sa.Text(), nullable=True),
    sa.Column('quoted_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('actor_kind', sa.String(length=20), nullable=False),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('is_quote_bearing', sa.Boolean(), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_identifier', sa.String(length=300), nullable=True),
    sa.Column('source_thread_identifier', sa.String(length=300), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('extractor_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_interaction_campaign_id_campaign'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], name=op.f('fk_interaction_contact_id_contact'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_interaction_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_interaction_vehicle_id_vehicle'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction')),
    sa.UniqueConstraint('source_system', 'source_identifier', name='uq_interaction_source')
    )
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.create_index('ix_interaction_dealer_time', ['dealer_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_interaction_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_interaction_review', ['needs_review'], unique=False)
        batch_op.create_index('ix_interaction_thread', ['source_thread_identifier'], unique=False)

    op.create_table('behavior_signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('polarity', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_behavior_signal_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_behavior_signal_interaction_id_interaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_behavior_signal'))
    )
    with op.batch_alter_table('behavior_signal', schema=None) as batch_op:
        batch_op.create_index('ix_signal_dealer', ['dealer_id', 'dimension'], unique=False)
        batch_op.create_index('ix_signal_dedupe', ['dedupe_key'], unique=True)

    op.create_table('commitment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('party', sa.String(length=20), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_interaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_commitment_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_interaction_id'], ['interaction.id'], name=op.f('fk_commitment_evidence_interaction_id_interaction'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_commitment_interaction_id_interaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commitment'))
    )
    with op.batch_alter_table('commitment', schema=None) as batch_op:
        batch_op.create_index('ix_commitment_dealer_status', ['dealer_id', 'status'], unique=False)

    op.create_table('email_source',
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('provider_thread_id', sa.String(length=200), nullable=True),
    sa.Column('rfc822_message_id', sa.String(length=400), nullable=True),
    sa.Column('in_reply_to', sa.String(length=400), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('from_email', sa.String(length=320), nullable=True),
    sa.Column('to_emails', sa.Text(), nullable=True),
    sa.Column('cc_emails', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('label_ids', sa.String(length=500), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('mime_summary', sa.String(length=500), nullable=True),
    sa.Column('history_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_email_source_interaction_id_interaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interaction_id', name=op.f('pk_email_source'))
    )
    with op.batch_alter_table('email_source', schema=None) as batch_op:
        batch_op.create_index('ix_email_provider_msg', ['provider', 'provider_message_id'], unique=True)
        batch_op.create_index('ix_email_rfc822', ['rfc822_message_id'], unique=False)

    op.create_table('llm_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('purpose', sa.String(length=60), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('schema_name', sa.String(length=120), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_llm_run_dealer_id_dealer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_llm_run_interaction_id_interaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_run'))
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_offer_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('quoted_at', sa.DateTime(), nullable=False),
    sa.Column('msrp_cents', sa.Integer(), nullable=True),
    sa.Column('advertised_price_cents', sa.Integer(), nullable=True),
    sa.Column('selling_price_cents', sa.Integer(), nullable=True),
    sa.Column('discount_cents', sa.Integer(), nullable=True),
    sa.Column('destination_cents', sa.Integer(), nullable=True),
    sa.Column('doc_fee_cents', sa.Integer(), nullable=True),
    sa.Column('processing_fee_cents', sa.Integer(), nullable=True),
    sa.Column('other_taxable_fees_cents', sa.Integer(), nullable=True),
    sa.Column('other_non_tax_fees_cents', sa.Integer(), nullable=True),
    sa.Column('tax_cents', sa.Integer(), nullable=True),
    sa.Column('registration_cents', sa.Integer(), nullable=True),
    sa.Column('title_fee_cents', sa.Integer(), nullable=True),
    sa.Column('quoted_otd_cents', sa.Integer(), nullable=True),
    sa.Column('financing_required', sa.Boolean(), nullable=True),
    sa.Column('financing_provider', sa.String(length=120), nullable=True),
    sa.Column('apr_bp', sa.Integer(), nullable=True),
    sa.Column('financing_term_months', sa.Integer(), nullable=True),
    sa.Column('minimum_financed_cents', sa.Integer(), nullable=True),
    sa.Column('minimum_loan_months', sa.Integer(), nullable=True),
    sa.Column('prepayment_penalty', sa.Boolean(), nullable=True),
    sa.Column('discount_clawback', sa.Boolean(), nullable=True),
    sa.Column('clawback_terms', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('deadline_note', sa.String(length=300), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_offer_campaign_id_campaign'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_offer_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_offer_interaction_id_interaction'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_offer_id'], ['offer.id'], name=op.f('fk_offer_supersedes_offer_id_offer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_offer_vehicle_id_vehicle'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer'))
    )
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.create_index('ix_offer_current', ['dealer_id', 'is_current'], unique=False)
        batch_op.create_index('ix_offer_dealer_version', ['dealer_id', 'version'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('asked_by', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=True),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answered_interaction_id', sa.Integer(), nullable=True),
    sa.Column('answer_summary', sa.Text(), nullable=True),
    sa.Column('asked_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answered_interaction_id'], ['interaction.id'], name=op.f('fk_question_answered_interaction_id_interaction'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_question_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_question_interaction_id_interaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index('ix_question_dealer_status', ['dealer_id', 'status'], unique=False)

    op.create_table('state_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=40), nullable=True),
    sa.Column('to_state', sa.String(length=40), nullable=False),
    sa.Column('reason_code', sa.String(length=60), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=60), nullable=True),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('was_suppressed_by_pin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_state_transition_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_state_transition_interaction_id_interaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_state_transition'))
    )
    with op.batch_alter_table('state_transition', schema=None) as batch_op:
        batch_op.create_index('ix_transition_dealer', ['dealer_id', 'created_at'], unique=False)

    op.create_table('transcript_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('speaker_label', sa.String(length=80), nullable=True),
    sa.Column('speaker_party', sa.String(length=20), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_transcript_segment_interaction_id_interaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_segment'))
    )
    with op.batch_alter_table('transcript_segment', schema=None) as batch_op:
        batch_op.create_index('ix_segment_interaction', ['interaction_id', 'index'], unique=False)

    op.create_table('transcript_source',
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('speaker_count', sa.Integer(), nullable=True),
    sa.Column('transcription_engine', sa.String(length=80), nullable=True),
    sa.Column('transcription_confidence', sa.Float(), nullable=True),
    sa.Column('audio_blob_path', sa.String(length=500), nullable=True),
    sa.Column('diarization_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_transcript_source_interaction_id_interaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interaction_id', name=op.f('pk_transcript_source'))
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('blob_path', sa.String(length=500), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_engine', sa.String(length=80), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_document_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_document_interaction_id_interaction'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], name=op.f('fk_document_offer_id_offer'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('ix_document_sha', ['sha256'], unique=False)

    op.create_table('draft_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('in_reply_to_interaction_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('strategy_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=False),
    sa.Column('llm_run_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_interaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], name=op.f('fk_draft_message_contact_id_contact'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_draft_message_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['in_reply_to_interaction_id'], ['interaction.id'], name=op.f('fk_draft_message_in_reply_to_interaction_id_interaction'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_run_id'], ['llm_run.id'], name=op.f('fk_draft_message_llm_run_id_llm_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_interaction_id'], ['interaction.id'], name=op.f('fk_draft_message_sent_interaction_id_interaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_message'))
    )
    with op.batch_alter_table('draft_message', schema=None) as batch_op:
        batch_op.create_index('ix_draft_dealer_status', ['dealer_id', 'status'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=300), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_notification_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_notification_interaction_id_interaction'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], name=op.f('fk_notification_offer_id_offer'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_dedupe', ['dedupe_key'], unique=True)
        batch_op.create_index('ix_notification_unread', ['read_at', 'created_at'], unique=False)

    op.create_table('offer_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('is_dealer_controlled', sa.Boolean(), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=True),
    sa.Column('mandatory_claimed', sa.Boolean(), nullable=True),
    sa.Column('already_installed', sa.Boolean(), nullable=True),
    sa.Column('user_wants', sa.Boolean(), nullable=False),
    sa.Column('removable_confirmed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], name=op.f('fk_offer_line_offer_id_offer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_line'))
    )
    op.create_table('fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(length=120), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_datetime', sa.DateTime(), nullable=True),
    sa.Column('value_unit', sa.String(length=20), nullable=True),
    sa.Column('display_value', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('transcript_segment_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('llm_run_id', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('quote_start', sa.Integer(), nullable=True),
    sa.Column('quote_end', sa.Integer(), nullable=True),
    sa.Column('asserted_by_party', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_fact_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_fact_document_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name=op.f('fk_fact_interaction_id_interaction'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_run_id'], ['llm_run.id'], name=op.f('fk_fact_llm_run_id_llm_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], name=op.f('fk_fact_offer_id_offer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['fact.id'], name=op.f('fk_fact_superseded_by_id_fact'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcript_segment_id'], ['transcript_segment.id'], name=op.f('fk_fact_transcript_segment_id_transcript_segment'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact'))
    )
    with op.batch_alter_table('fact', schema=None) as batch_op:
        batch_op.create_index('ix_fact_dealer', ['dealer_id', 'attribute'], unique=False)
        batch_op.create_index('ix_fact_subject', ['subject_type', 'subject_id', 'attribute', 'status'], unique=False)

    op.create_table('contradiction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(length=120), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('fact_a_id', sa.Integer(), nullable=True),
    sa.Column('fact_b_id', sa.Integer(), nullable=True),
    sa.Column('interaction_a_id', sa.Integer(), nullable=True),
    sa.Column('interaction_b_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail_a', sa.Text(), nullable=True),
    sa.Column('detail_b', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('detected_by', sa.String(length=20), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name=op.f('fk_contradiction_dealer_id_dealer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_a_id'], ['fact.id'], name=op.f('fk_contradiction_fact_a_id_fact'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fact_b_id'], ['fact.id'], name=op.f('fk_contradiction_fact_b_id_fact'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_a_id'], ['interaction.id'], name=op.f('fk_contradiction_interaction_a_id_interaction'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_b_id'], ['interaction.id'], name=op.f('fk_contradiction_interaction_b_id_interaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contradiction'))
    )
    with op.batch_alter_table('contradiction', schema=None) as batch_op:
        batch_op.create_index('ix_contradiction_dealer', ['dealer_id', 'status'], unique=False)
        batch_op.create_index('ix_contradiction_dedupe', ['dedupe_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contradiction', schema=None) as batch_op:
        batch_op.drop_index('ix_contradiction_dedupe')
        batch_op.drop_index('ix_contradiction_dealer')

    op.drop_table('contradiction')
    with op.batch_alter_table('fact', schema=None) as batch_op:
        batch_op.drop_index('ix_fact_subject')
        batch_op.drop_index('ix_fact_dealer')

    op.drop_table('fact')
    op.drop_table('offer_line')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_unread')
        batch_op.drop_index('ix_notification_dedupe')

    op.drop_table('notification')
    with op.batch_alter_table('draft_message', schema=None) as batch_op:
        batch_op.drop_index('ix_draft_dealer_status')

    op.drop_table('draft_message')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('ix_document_sha')

    op.drop_table('document')
    op.drop_table('transcript_source')
    with op.batch_alter_table('transcript_segment', schema=None) as batch_op:
        batch_op.drop_index('ix_segment_interaction')

    op.drop_table('transcript_segment')
    with op.batch_alter_table('state_transition', schema=None) as batch_op:
        batch_op.drop_index('ix_transition_dealer')

    op.drop_table('state_transition')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index('ix_question_dealer_status')

    op.drop_table('question')
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_index('ix_offer_dealer_version')
        batch_op.drop_index('ix_offer_current')

    op.drop_table('offer')
    op.drop_table('llm_run')
    with op.batch_alter_table('email_source', schema=None) as batch_op:
        batch_op.drop_index('ix_email_rfc822')
        batch_op.drop_index('ix_email_provider_msg')

    op.drop_table('email_source')
    with op.batch_alter_table('commitment', schema=None) as batch_op:
        batch_op.drop_index('ix_commitment_dealer_status')

    op.drop_table('commitment')
    with op.batch_alter_table('behavior_signal', schema=None) as batch_op:
        batch_op.drop_index('ix_signal_dedupe')
        batch_op.drop_index('ix_signal_dealer')

    op.drop_table('behavior_signal')
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_index('ix_interaction_thread')
        batch_op.drop_index('ix_interaction_review')
        batch_op.drop_index('ix_interaction_hash')
        batch_op.drop_index('ix_interaction_dealer_time')

    op.drop_table('interaction')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index('ix_vehicle_vin')

    op.drop_table('vehicle')
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_index('ix_contact_email')

    op.drop_table('contact')
    with op.batch_alter_table('dealer', schema=None) as batch_op:
        batch_op.drop_index('ix_dealer_state')

    op.drop_table('dealer')
    with op.batch_alter_table('sync_state', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_provider')

    op.drop_table('sync_state')
    op.drop_table('negotiation_state')
    op.drop_table('campaign')
    op.drop_table('buyer_profile')
    # ### end Alembic commands ###
